Repository cupcode-git/cupcode, pull requests merged in 2019-06, with the labels that each got.

#1 CSS, Hero
  css/bootstrap.min.css
  css/style.css
  index.html
Labels: enhancement

#2 Correções de bugs
  css/style.css
  images/ (18).png
  images/bg-cupcode-salmao.jpg
  images/logo.png
  images/logo10.png
  images/logo12.png
  images/logo13.png
  images/logo14.png
  images/logo15.png
  images/logo16.png
  images/logo17.png
  images/logo18.png
  images/logo19.png
  images/logo2.png
  images/logo20.png
  images/logo21.png
  images/logo22.png
  images/logo23.png
  images/logo24.png
  images/logo25.png
  images/logo26.png
  images/logo27.png
  images/logo28.png
  images/logo29.png
  images/logo3.png
  images/logo30.png
  images/logo31.png
  images/logo32.png
  images/logo33.png
  images/logo34.png
  images/logo35.png
  images/logo36.png
  images/logo37.png
  images/logo38.png
  images/logo39.png
  images/logo4.png
  images/logo40.png
  images/logo5.png
  images/logo6.png
  images/logo7.png
  images/logo8.png
  images/logo9.png
  index.html
Labels: bug, enhancement

#3 Correção de bugs
  css/bootstrap.min.css
  css/style.css
  index.html
Labels: bug

#8 arrumei o contato colocando padding 0 e mudei o tamanho da coluna
  css/style.css
  index.html
Labels: enhancement

#9 colocando imagem no background
  css/style.css
  images/bg-cup-salmao.jpg
  images/bg-cv.jpg
  images/bg-hero.jpg
Labels: enhancement

#13 icone cup e botão
  images/bg-hero.jpg
  images/favicon.png
  index.html
Labels: enhancement

#16 arrumei os background do site e galeria
  css/style.css
  images/gallery-light1.jpg
  images/gallery-light2.jpg
  images/gallery-light6.jpg
  images/portfolio1.jpg
  images/single-portfolio1.jpg
  index.html
Labels: bug, enhancement

#18 Correção de posicionamento e imagem nova
  css/settings.css
  images/bg-contato.jpg
Labels: bug, enhancement
